# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n8JKuNj8E7a3J0yKKxJyVC3xD5AtSFva
"""

import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.offline import iplot, plot
from plotly.subplots import make_subplots

df = pd.read_csv("/content/starbucks.csv")
df.head(5)

print(f"Number of Columns :{df.shape[1]}")
print(f"Number of Rows :{df.shape[0]}")

df.info

df.isnull().sum()

df.describe(exclude = np.number)

pd.DataFrame({
    'count':df.shape[0],
    'Nulls':df.isnull().sum(),
    'nulls%':df.isnull().sum()*100,
    'cardinality': df.nunique(),
})

cols = df.columns
df.columns = df.columns.str.strip()
df.dtypes

df.head(5)

df['Beverage_category'].unique()

plt.title('Beverage catergories count')

sns.countplot(data=df, y='Beverage_category')
plt.show()

df['Caffeine (mg)'].unique()

df = df.dropna(subset=['Caffeine (mg)'])
df = df[~df['Caffeine (mg)'].isin(['Varies', 'varies'])]

df['Caffeine (mg)'] = pd.to_numeric(df['Caffeine (mg)'], errors='coerce')
df['Caffeine (mg)'].dtypes

plt.figure(figsize=(8,5))

plt.title('Relationship of Calories and Caffeine (mg)')

sns.regplot(df, x='Caffeine (mg)', y='Calories')
plt.show()

average_calories_per_category = df.groupby('Beverage_category')['Calories'].mean().reset_index()

plt.figure(figsize=(7,4))

plt.xticks(rotation=45, ha='right')

plt.title('Average Calories in Each Beverage Category')

sns.barplot(data=average_calories_per_category, x='Beverage_category', y='Calories')
plt.show

nutri_col = ['Calories', 'Total Fat (g)', 'Sugars (g)', 'Protein (g)']

correl_df = df[nutri_col].copy()

correl_df['Total Fat (g)'] = pd.to_numeric(correl_df['Total Fat (g)'], errors='coerce')

sns.pairplot(data=correl_df, corner=True)
plt.show()

dietary_fib = df.groupby('Beverage_category')[['Dietary Fibre (g)']]
plt.xticks(rotation=45, ha='right')
sns.boxplot(data=df, x='Beverage_category', y='Dietary Fibre (g)')

scatterplot = sns.scatterplot(data=df, x='Total Carbohydrates (g)', y='Sugars (g)', hue='Beverage_category')

scatterplot.legend(loc='center left', bbox_to_anchor=(1, 0.5), title="Beverage Category")

plt.show()

